sudo: required
dist: trusty
language: csharp
solution: MvcApplicationTest.sln
mono:
  - beta
dotnet: 1.0.3

install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore MvcApplicationTest.sln
  - dotnet restore MvcApplicationTest.sln

script:
  - msbuild /t:Jenkins ci.msbuild
