sudo: required
dist: trusty
language: csharp
solution: MvcApplicationTest.sln
mono:
  - beta
dotnet: 1.0.3

install:
  - nuget restore MvcApplicationTest.sln
  - dotnet restore MvcApplicationTest.sln

script:
  - msbuild /t:Jenkins ci.msbuild
