sudo: required
dist: trusty
language: csharp
solution: MvcApplicationTest.sln
mono:
  - beta
dotnet: 1.0.3

install:
  - mono .nuget/nuget.exe restore MvcApplicationTest.sln
  - dotnet restore MvcApplicationTest.sln
  - mono .nuget/nuget.exe install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner

script:
  - msbuild /t:TravisCI ci.msbuild
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./MvcApplicationTest.Tests/bin/Release/MvcApplicationTest.Tests.dll
